name: BridgeWars
version: '${project.version}'
main: ivanhauu.tech.bridgewars.BridgeWars
api-version: '1.21'
author: ivnls
commands:
  fight:
    description: Vá Lutar!
  spawn:
    description: Vá ao Spawn!
  ptop:
    description: Os melhores players!
  battles:
    description: Partidas em andamento!
  Spectate:
    description: Assista á partidas!